name: Build, Push, and Update Deployment

on:
  workflow_dispatch:
    #branches:
      #- main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório 
      - name: Checkout app repository
        uses: actions/checkout@v4

      # Configura Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Cria variáveis de versão
      - name: Set image version variables
        id: vars
        run: |
          echo "RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      # Build e push da imagem para o Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            christianfernandesprofissional/py-app:${{ env.IMAGE_VERSION }}

      # Mostra imagens locais 
      - name: Show docker images
        run: docker images

      # Adiciona chave SSH para acessar o outro repositório
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Clona o repositório de manifests 
      - name: Clone manifests repository
        run: |
          git clone git@github.com:christianfernandesprofissional/py-app-manifests.git
          cd py-app-manifests
          ls -la

      # Atualiza a imagem no deployment.yaml
      - name: Update deployment image version
        run: |
          cd py-app-manifests
          cd manifests
          ls -la
          sed -i "s|image: christianfernandesprofissional/py-app:.*|image: christianfernandesprofissional/py-app:${IMAGE_VERSION}|" deployment.yaml

      # Faz o commit e o push em uma branch temporária
      - name: Commit and push changes to new branch
        run: |
          cd py-app-manifests
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

          # Cria uma branch temporária única
          BRANCH_NAME="auto/update-image-${{ env.IMAGE_VERSION }}"
          git checkout -b "$BRANCH_NAME"

          git add .
          git commit -m "Update image to version ${IMAGE_VERSION}"
          git push origin "$BRANCH_NAME"

      # Cria o Pull Request da branch temporária para a main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN_MANIFESTS }}
          base: main
          branch: auto/update-image-${{ env.IMAGE_VERSION }}
          title: "Update image to version ${{ env.IMAGE_VERSION }}"
          body: |
            This PR updates the image tag to `${{ env.IMAGE_VERSION }}`.
          delete-branch: true
