name: Build, Push, and Update Deployment

on: 
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório atual 
      - name: Checkout app repository
        uses: actions/checkout@v4

      # Configura Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Cria variáveis de versão
      - name: Set image version variables
        id: vars
        run: |
          echo "RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      # Build e push da imagem
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: christianfernandesprofissional/py-app:${{ env.IMAGE_VERSION }}

      # Mostra imagens locais (debug opcional)
      - name: Show docker images
        run: docker images

      # Checkout do repositório de manifests
      - name: Checkout manifests repository
        uses: actions/checkout@v4
        with:
          repository: christianfernandesprofissional/py-app-manifests
          token: ${{ secrets.TOKEN_MANIFESTS }}
          path: py-app-manifests

      # Atualiza o arquivo deployment.yaml
      - name: Update deployment image version
        id: create-pull-request 
        run: |
          cd py-app-manifests/manifests
          sed -i "s|image: christianfernandesprofissional/py-app:.*|image: christianfernandesprofissional/py-app:${IMAGE_VERSION}|" deployment.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN_MANIFESTS }}
          base: main
          branch: auto/update-image-${{ env.IMAGE_VERSION }}
          title: "Update image to version ${{ env.IMAGE_VERSION }}"
          body: |
            This PR updates the image tag to `${{ env.IMAGE_VERSION }}`.
          delete-branch: true
          path: ./py-app-manifests

      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.TOKEN_MANIFESTS }}
          repository: christianfernandesprofissional/py-app-manifests
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash
